package com.hzpd.modle.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ALBUM_BEAN_DB".
 */
public class AlbumBeanDB {

    private Long id;
    private String pid;
    private String title;
    private String count;
    private String siteid;
    private String create_time;
    private String json_url;

    public AlbumBeanDB() {
    }

    public AlbumBeanDB(Long id) {
        this.id = id;
    }

    public AlbumBeanDB(Long id, String pid, String title, String count, String siteid, String create_time, String json_url) {
        this.id = id;
        this.pid = pid;
        this.title = title;
        this.count = count;
        this.siteid = siteid;
        this.create_time = create_time;
        this.json_url = json_url;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPid() {
        return pid;
    }

    public void setPid(String pid) {
        this.pid = pid;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getCount() {
        return count;
    }

    public void setCount(String count) {
        this.count = count;
    }

    public String getSiteid() {
        return siteid;
    }

    public void setSiteid(String siteid) {
        this.siteid = siteid;
    }

    public String getCreate_time() {
        return create_time;
    }

    public void setCreate_time(String create_time) {
        this.create_time = create_time;
    }

    public String getJson_url() {
        return json_url;
    }

    public void setJson_url(String json_url) {
        this.json_url = json_url;
    }

}
