package com.hzpd.modle.db;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        UserLogDao.createTable(db, ifNotExists);
        AlbumBeanDBDao.createTable(db, ifNotExists);
        AlbumItemBeanDBDao.createTable(db, ifNotExists);
        NewsBeanDBDao.createTable(db, ifNotExists);
        NewsChannelBeanDBDao.createTable(db, ifNotExists);
        PushBeanDBDao.createTable(db, ifNotExists);
        VideoItemBeanDbDao.createTable(db, ifNotExists);
        ZhuantiBeanDBDao.createTable(db, ifNotExists);
        NewsItemBeanForCollectionDao.createTable(db, ifNotExists);
        JsonbeanDao.createTable(db, ifNotExists);
        NewsJumpBeanDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        UserLogDao.dropTable(db, ifExists);
        AlbumBeanDBDao.dropTable(db, ifExists);
        AlbumItemBeanDBDao.dropTable(db, ifExists);
        NewsBeanDBDao.dropTable(db, ifExists);
        NewsChannelBeanDBDao.dropTable(db, ifExists);
        PushBeanDBDao.dropTable(db, ifExists);
        VideoItemBeanDbDao.dropTable(db, ifExists);
        ZhuantiBeanDBDao.dropTable(db, ifExists);
        NewsItemBeanForCollectionDao.dropTable(db, ifExists);
        JsonbeanDao.dropTable(db, ifExists);
        NewsJumpBeanDao.dropTable(db, ifExists);
        ZhuantiBeanDBDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(UserLogDao.class);
        registerDaoClass(AlbumBeanDBDao.class);
        registerDaoClass(AlbumItemBeanDBDao.class);
        registerDaoClass(NewsBeanDBDao.class);
        registerDaoClass(NewsChannelBeanDBDao.class);
        registerDaoClass(PushBeanDBDao.class);
        registerDaoClass(VideoItemBeanDbDao.class);
        registerDaoClass(ZhuantiBeanDBDao.class);
        registerDaoClass(NewsItemBeanForCollectionDao.class);
        registerDaoClass(JsonbeanDao.class);
        registerDaoClass(NewsJumpBeanDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
