package com.hzpd.modle.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "JSONBEAN".
 */
public class Jsonbean {

    private Long id;
    private String fid;
    private String data;

    public Jsonbean() {
    }

    public Jsonbean(Long id) {
        this.id = id;
    }

    public Jsonbean(Long id, String fid, String data) {
        this.id = id;
        this.fid = fid;
        this.data = data;
    }
	
	    public Jsonbean(String mfid, String mdata) {
        this.fid = mfid;
        this.data = mdata;
    }


    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFid() {
        return fid;
    }

    public void setFid(String fid) {
        this.fid = fid;
    }

    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data;
    }

}
