package com.hzpd.modle.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.text.TextUtils;

import com.hzpd.modle.CollectionDataBean;
import com.hzpd.modle.CollectionJsonBean;
import com.hzpd.modle.ImageListSubBean;
import com.hzpd.modle.ImgListBean;
import com.hzpd.modle.NewsBean;
import com.hzpd.modle.VideoItemBean;

import java.util.List;

/**
 * Entity mapped to table "NEWS_ITEM_BEAN_FOR_COLLECTION".
 */
public class NewsItemBeanForCollection {

    private Long id;
    private String collectionid;
    private String type;
    private String datetime;
    private String nid;
    private String tid;
    private String title;
    private String time;
    private String imgs;
    private String json_url;
    private String rtype;
    private String collect_time;
    private String copyfrom;
    private String fav;
    private String comcount;
    private String like;
    private String unlike;

    public NewsItemBeanForCollection() {
    }

    public NewsItemBeanForCollection(Long id) {
        this.id = id;
    }

    public NewsItemBeanForCollection(Long id, String collectionid, String type, String datetime, String nid, String tid, String title, String time, String imgs, String json_url, String rtype, String collect_time, String copyfrom, String fav, String comcount, String like, String unlike) {
        this.id = id;
        this.collectionid = collectionid;
        this.type = type;
        this.datetime = datetime;
        this.nid = nid;
        this.tid = tid;
        this.title = title;
        this.time = time;
        this.imgs = imgs;
        this.json_url = json_url;
        this.rtype = rtype;
        this.collect_time = collect_time;
        this.copyfrom = copyfrom;
        this.fav = fav;
        this.comcount = comcount;
        this.like = like;
        this.unlike = unlike;
    }
	
	
	
    public NewsItemBeanForCollection(NewsBean newsbean) {
        nid = newsbean.getNid();
        title = newsbean.getTitle();
        tid = newsbean.getTid();
        type = "1";
        time = newsbean.getUpdate_time();
        json_url = newsbean.getJson_url();
        copyfrom=newsbean.getCopyfrom();
        fav=newsbean.getFav();
        comcount=newsbean.getComcount();
        like=newsbean.getLike();
        unlike=newsbean.getUnlike();
//		String limgs[] = newsbean.getImgs();
//		if (null != limgs && limgs.length > 0) {
//			imgs = limgs[0];
//		}
        String[] nbImgs = newsbean.getImgs();
        StringBuilder sb = new StringBuilder();
        if (null != nbImgs) {
            for (String s : nbImgs) {
                sb.append(s);
                sb.append(",");
            }
            if (sb.length() > 1) {
                imgs = sb.substring(0, sb.length() - 1);
            }
        }
        collect_time = System.currentTimeMillis()+"";
    }

    public NewsItemBeanForCollection(NewsBean newsbean, String html5) {
        nid = newsbean.getNid();
        title = newsbean.getTitle();
        tid = newsbean.getTid();
        type = "4";
        time = newsbean.getUpdate_time();
        json_url = newsbean.getJson_url();
        copyfrom=newsbean.getCopyfrom();
        fav=newsbean.getFav();
        comcount=newsbean.getComcount();
        like=newsbean.getLike();
        unlike=newsbean.getUnlike();
//		String limgs[] = newsbean.getImgs();
//		if (null != limgs && limgs.length > 0) {
//			imgs = limgs[0];
//		}
        String[] nbImgs = newsbean.getImgs();
        StringBuilder sb = new StringBuilder();
        if (null != nbImgs) {
            for (String s : nbImgs) {
                sb.append(s);
                sb.append(",");
            }
            if (sb.length() > 1) {
                imgs = sb.substring(0, sb.length() - 1);
            }
        }

        collect_time = System.currentTimeMillis()+"";
    }

    public NewsItemBeanForCollection(ImgListBean imglistbean) {
        nid = imglistbean.getPid();
        title = imglistbean.getTitle();
        type = "2";
        time = imglistbean.getCreate_time();
        json_url = imglistbean.getJson_url();
        collect_time = System.currentTimeMillis()+"";
        copyfrom=imglistbean.getCopyfrom();
        fav=imglistbean.getFav();
        comcount=imglistbean.getComcount();
        List<ImageListSubBean> li = imglistbean.getSubphoto();
        if (li.size() > 0) {
            imgs= li.get(0).getSubphoto();
        }

    }

    public NewsItemBeanForCollection(VideoItemBean vib) {
        nid = vib.getVid();
        title = vib.getTitle();
        type = "3";
        time = vib.getTime();
        json_url = vib.getJson_url();
        collect_time = System.currentTimeMillis()+"";
        imgs = vib.getMainpic();
        copyfrom=vib.getCopyfrom();
        fav=vib.getFav();
        comcount=vib.getComcount();
    }

    public NewsBean getNewsBean() {
        NewsBean nb = new NewsBean();
        nb.setNid(nid);
        nb.setJson_url(json_url);

        nb.setTid(tid);
        nb.setTitle(title);
        nb.setType(type);
        nb.setUpdate_time(time);

        nb.setCopyfrom(copyfrom);
        nb.setFav(fav);
        nb.setComcount(comcount);

//		if (null != imgs) {
//			String s[] = new String[3];
//			s[0] = imgs;
//			nb.setImgs(s);
//		}

        if (!TextUtils.isEmpty(imgs)) {
            String[] nbImgs = imgs.split(",");
            nb.setImgs(nbImgs);
        }

        return nb;
    }

    public CollectionJsonBean getCollectionJsonBean() {
        CollectionJsonBean cb = new CollectionJsonBean();
        String[] nbImgs=null;
        if (!TextUtils.isEmpty(imgs)) {
            nbImgs = imgs.split(",");
        }
        CollectionDataBean cdb = new CollectionDataBean(nid, tid, title, time, nbImgs, json_url, rtype,copyfrom,fav,comcount);
//		CollectionDataBean cdb = new CollectionDataBean(nid, tid, title, time, thumb, json_url, rtype);
        cb.setData(cdb);
        cb.setDatetime(time);
        cb.setType(type);

        return cb;
    }

    public VideoItemBean getVideoItemBean() {
        VideoItemBean vib = new VideoItemBean();
        vib.setJson_url(this.json_url);
        vib.setMainpic(this.imgs);
        vib.setTitle(this.title);
        vib.setVid(this.nid);
        vib.setTime(this.time);
        vib.setCopyfrom(this.copyfrom);
        vib.setFav(this.fav);
        vib.setComcount(this.comcount);
        return vib;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCollectionid() {
        return collectionid;
    }

    public void setCollectionid(String collectionid) {
        this.collectionid = collectionid;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getDatetime() {
        return datetime;
    }

    public void setDatetime(String datetime) {
        this.datetime = datetime;
    }

    public String getNid() {
        return nid;
    }

    public void setNid(String nid) {
        this.nid = nid;
    }

    public String getTid() {
        return tid;
    }

    public void setTid(String tid) {
        this.tid = tid;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public String getImgs() {
        return imgs;
    }

    public void setImgs(String imgs) {
        this.imgs = imgs;
    }

    public String getJson_url() {
        return json_url;
    }

    public void setJson_url(String json_url) {
        this.json_url = json_url;
    }

    public String getRtype() {
        return rtype;
    }

    public void setRtype(String rtype) {
        this.rtype = rtype;
    }

    public String getCollect_time() {
        return collect_time;
    }

    public void setCollect_time(String collect_time) {
        this.collect_time = collect_time;
    }

    public String getCopyfrom() {
        return copyfrom;
    }

    public void setCopyfrom(String copyfrom) {
        this.copyfrom = copyfrom;
    }

    public String getFav() {
        return fav;
    }

    public void setFav(String fav) {
        this.fav = fav;
    }

    public String getComcount() {
        return comcount;
    }

    public void setComcount(String comcount) {
        this.comcount = comcount;
    }

    public String getLike() {
        return like;
    }

    public void setLike(String like) {
        this.like = like;
    }

    public String getUnlike() {
        return unlike;
    }

    public void setUnlike(String unlike) {
        this.unlike = unlike;
    }

}
