package com.hzpd.modle.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.text.TextUtils;

import com.hzpd.modle.VideoItemBean;

/**
 * Entity mapped to table "VIDEO_ITEM_BEAN_DB".
 */
public class VideoItemBeanDb {

    private Long id;
    private String vid;
    private String title;
    private String time;
    private String mainpic;
    private String json_url;

    public VideoItemBeanDb() {
    }

    public VideoItemBeanDb(Long id) {
        this.id = id;
    }

    public VideoItemBeanDb(Long id, String vid, String title, String time, String mainpic, String json_url) {
        this.id = id;
        this.vid = vid;
        this.title = title;
        this.time = time;
        this.mainpic = mainpic;
        this.json_url = json_url;
    }
	
	    public VideoItemBeanDb(VideoItemBean bean) {
        if (!TextUtils.isEmpty(bean.getVid())) {
            if (TextUtils.isDigitsOnly(bean.getVid())) {
                try {
                    vid = bean.getVid();
                } catch (Exception e) {
                    vid = null;
                }
            }
        }
        this.time = bean.getTime();
        this.title = bean.getTitle();
        this.mainpic = bean.getMainpic();
        this.json_url = bean.getJson_url();
    }

    public VideoItemBean getVideoItemBean() {
        VideoItemBean bean = new VideoItemBean();
        bean.setVid(vid + "");
        bean.setTitle(title);
        bean.setTime(time);
        bean.setMainpic(mainpic);
        bean.setJson_url(json_url);

        return bean;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getVid() {
        return vid;
    }

    public void setVid(String vid) {
        this.vid = vid;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public String getMainpic() {
        return mainpic;
    }

    public void setMainpic(String mainpic) {
        this.mainpic = mainpic;
    }

    public String getJson_url() {
        return json_url;
    }

    public void setJson_url(String json_url) {
        this.json_url = json_url;
    }

}
