package com.hzpd.modle.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ZHUANTI_BEAN_DB".
 */
public class ZhuantiBeanDB {

    private Long id;
    private String nid;
    private String tagId;
    private String authorname;
    private String title;
    private String sid;
    private String tid;
    private String outline;
    private String type;
    private String update_time;
    private String json_url;
    private String imgs;
    private String rtype;
    private String comcount;
    private String sort_order;
    private String subjectsort;
    private String status;
    private String comflag;
    private String isreaded;
    private String columnid;
    private String copyfrom;
    private String fav;
    private String attname;
    private String like;
    private String unlike;

    public ZhuantiBeanDB() {
    }

    public ZhuantiBeanDB(Long id) {
        this.id = id;
    }

    public ZhuantiBeanDB(Long id, String nid, String tagId, String authorname, String title, String sid, String tid, String outline, String type, String update_time, String json_url, String imgs, String rtype, String comcount, String sort_order, String subjectsort, String status, String comflag, String isreaded, String columnid, String copyfrom, String fav, String attname, String like, String unlike) {
        this.id = id;
        this.nid = nid;
        this.tagId = tagId;
        this.authorname = authorname;
        this.title = title;
        this.sid = sid;
        this.tid = tid;
        this.outline = outline;
        this.type = type;
        this.update_time = update_time;
        this.json_url = json_url;
        this.imgs = imgs;
        this.rtype = rtype;
        this.comcount = comcount;
        this.sort_order = sort_order;
        this.subjectsort = subjectsort;
        this.status = status;
        this.comflag = comflag;
        this.isreaded = isreaded;
        this.columnid = columnid;
        this.copyfrom = copyfrom;
        this.fav = fav;
        this.attname = attname;
        this.like = like;
        this.unlike = unlike;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNid() {
        return nid;
    }

    public void setNid(String nid) {
        this.nid = nid;
    }

    public String getTagId() {
        return tagId;
    }

    public void setTagId(String tagId) {
        this.tagId = tagId;
    }

    public String getAuthorname() {
        return authorname;
    }

    public void setAuthorname(String authorname) {
        this.authorname = authorname;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getSid() {
        return sid;
    }

    public void setSid(String sid) {
        this.sid = sid;
    }

    public String getTid() {
        return tid;
    }

    public void setTid(String tid) {
        this.tid = tid;
    }

    public String getOutline() {
        return outline;
    }

    public void setOutline(String outline) {
        this.outline = outline;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getUpdate_time() {
        return update_time;
    }

    public void setUpdate_time(String update_time) {
        this.update_time = update_time;
    }

    public String getJson_url() {
        return json_url;
    }

    public void setJson_url(String json_url) {
        this.json_url = json_url;
    }

    public String getImgs() {
        return imgs;
    }

    public void setImgs(String imgs) {
        this.imgs = imgs;
    }

    public String getRtype() {
        return rtype;
    }

    public void setRtype(String rtype) {
        this.rtype = rtype;
    }

    public String getComcount() {
        return comcount;
    }

    public void setComcount(String comcount) {
        this.comcount = comcount;
    }

    public String getSort_order() {
        return sort_order;
    }

    public void setSort_order(String sort_order) {
        this.sort_order = sort_order;
    }

    public String getSubjectsort() {
        return subjectsort;
    }

    public void setSubjectsort(String subjectsort) {
        this.subjectsort = subjectsort;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getComflag() {
        return comflag;
    }

    public void setComflag(String comflag) {
        this.comflag = comflag;
    }

    public String getIsreaded() {
        return isreaded;
    }

    public void setIsreaded(String isreaded) {
        this.isreaded = isreaded;
    }

    public String getColumnid() {
        return columnid;
    }

    public void setColumnid(String columnid) {
        this.columnid = columnid;
    }

    public String getCopyfrom() {
        return copyfrom;
    }

    public void setCopyfrom(String copyfrom) {
        this.copyfrom = copyfrom;
    }

    public String getFav() {
        return fav;
    }

    public void setFav(String fav) {
        this.fav = fav;
    }

    public String getAttname() {
        return attname;
    }

    public void setAttname(String attname) {
        this.attname = attname;
    }

    public String getLike() {
        return like;
    }

    public void setLike(String like) {
        this.like = like;
    }

    public String getUnlike() {
        return unlike;
    }

    public void setUnlike(String unlike) {
        this.unlike = unlike;
    }

}
